// Generated by https://quicktype.io

export interface SeleniumSide {
    id: string;
    version: string;
    name: string;
    url: string;
    tests: Test[];
    suites: SeleniumSuite[];
    urls: string[];
    plugins: any[];
}

export interface SeleniumSuite {
    id: string;
    name: string;
    persistSession: boolean;
    parallel: boolean;
    timeout: number;
    tests: string[];
}

export interface Test {
    id: string;
    name: string;
    commands: Command[];
}

export interface Command {
    id: string;
    comment: string;
    command: string;
    target: string;
    targets: Array<string[]>;
    value: string;
    opensWindow?: boolean;
    windowHandleName?: string;
    windowTimeout?: number;
}
