// Generated by https://quicktype.io

export interface SideexJson {
    time: number;
    version: Version;
    suites: SideexSuite[];
}

export interface SideexSuite {
    title: string;
    enableOnPlaying: boolean;
    cases: Case[];
}

export interface Case {
    title: string;
    enableOnPlaying: boolean;
    networkSpeed: number;
    records: Record[];
}

export interface Record {
    name: string;
    target: Target;
    value: Target;
    pwt: { [key: string]: number };
    comment: boolean;
}

export interface Target {
    usedIndex: number;
    options: Option[];
    tac: string;
}

export interface Option {
    type: string;
    value: string;
}

export interface Version {
    sideex: number[];
    format: number[];
}
