import { openCommandFunc } from './recordCommand/openCommandFunc';
import { addSelectionFunc } from './recordCommand/addSelectionFunc';
import { removeSelectionFunc } from './recordCommand/removeSelectionFunc';
import { answerOnNextPromptCommandFunc } from './recordCommand/answerOnNextPromptCommandFunc';
import { assertPromptCommandFunc } from './recordCommand/assertPromptCommandFunc';
import { dragAndDropToObjectFunc } from './recordCommand/dragAndDropToObjectFunc';
import { setWindowSizeFunc } from './recordCommand/setWindowSizeFunc';
import { defaultFunc } from './recordCommand/defaultFunc';
import { Record } from './struct/sideexStruct';
import { Command } from './struct/seleniumStruct';
import { clickFunc } from './recordCommand/clickFunc';

//add different function to different command
export const commandFunc: {
    [key: string]: (
        command: Command,
        isCommandComment: boolean,
        urlArr?: string[],
    ) => Record;
} = {
    open: openCommandFunc,
    addSelection: addSelectionFunc,
    answerOnNextPrompt: answerOnNextPromptCommandFunc,
    assert: defaultFunc,
    assertAlert: defaultFunc,
    asserChecked: defaultFunc,
    assertConfirmation: defaultFunc,
    assertEditable: defaultFunc,
    assertElementPresent: defaultFunc,
    assertElementNotPresent: defaultFunc,
    assertNotChecked: defaultFunc,
    assertNotSelectedValue: defaultFunc,
    assertPrompt: assertPromptCommandFunc,
    assertSelectedValue: defaultFunc,
    assertSelectedLabel: defaultFunc,
    assertText: defaultFunc,
    assertTitle: defaultFunc,
    assertValue: defaultFunc,
    check: defaultFunc,
    chooseCancelOnNextConfirmation: defaultFunc,
    chooseCancelOnNextPrompt: defaultFunc,
    chooseOkOnNextConfirmation: defaultFunc,
    click: clickFunc,
    clickAt: defaultFunc,
    close: defaultFunc,
    debugger: defaultFunc,
    doubleClick: defaultFunc,
    coubleClickAt: defaultFunc,
    dragAndDropToObject: dragAndDropToObjectFunc,
    echo: defaultFunc,
    editContent: defaultFunc,
    else: defaultFunc,
    end: defaultFunc,
    executeScript: defaultFunc,
    executeAsyncScript: defaultFunc,
    if: defaultFunc,
    mouseDown: defaultFunc,
    mouseDownAt: defaultFunc,
    mouseMoveAt: defaultFunc,
    mouseOut: defaultFunc,
    mouseOver: defaultFunc,
    mouseUp: defaultFunc,
    mouseUpAt: defaultFunc,
    pause: defaultFunc,
    removeSelection: removeSelectionFunc,
    repeatIf: defaultFunc,
    run: defaultFunc,
    runScript: defaultFunc,
    select: defaultFunc,
    selectFrame: defaultFunc,
    selectWindow: defaultFunc,
    sendKeys: defaultFunc,
    setSpeed: defaultFunc,
    setWindowSize: setWindowSizeFunc,
    store: defaultFunc,
    storeAttribute: defaultFunc,
    storeJson: defaultFunc,
    storeText: defaultFunc,
    storeTitle: defaultFunc,
    storeValue: defaultFunc,
    storeWindowHandle: defaultFunc,
    storeXpathCount: defaultFunc,
    submit: defaultFunc,
    times: defaultFunc,
    type: defaultFunc,
    uncheckLocator: defaultFunc,
    verify: defaultFunc,
    verifyChecked: defaultFunc,
    verifyEditable: defaultFunc,
    verifyElementPresent: defaultFunc,
    verifyElementNotPresent: defaultFunc,
    verifyNotChecked: defaultFunc,
    verifyNotEditable: defaultFunc,
    verifyNotSelectedValue: defaultFunc,
    verifyNotText: defaultFunc,
    verifySelectedLabel: defaultFunc,
    verifySelectedValue: defaultFunc,
    verifyText: defaultFunc,
    verifyTitle: defaultFunc,
    verifyValue: defaultFunc,
    waitForElementEditable: defaultFunc,
    waitForElementNotEditable: defaultFunc,
    waitForElementNotPresent: defaultFunc,
    waitForElementNotVisible: defaultFunc,
    waitForElementPresent: defaultFunc,
    waitForElementVisibleLocator: defaultFunc,
    waitForTextLocatorText: defaultFunc,
    webdriverAnswerOnVisiblePrompt: defaultFunc,
    webdriverChooseCancelOnVisibleConfirmation: defaultFunc,
    webdriverChooseCancelOnVisiblePrompt: defaultFunc,
    webdriverChooseOkOnVisibleConfirmation: defaultFunc,
    while: defaultFunc,
};
